#!/bin/sh

# See also http://alankent.wordpress.com/2014/08/02/magento-2-progress-towards-installation-via-composer/

cd /var/www/magento2 

rm -rf htdocs
mkdir -p htdocs

curl -sS https://getcomposer.org/installer | php
php composer.phar install --profile

# TEMPORARY FIX - a unit test snuck into alpha99 in wrong directory
rm -rf htdocs/app/code/Magento/CatalogSearch/Model/Search/CatalogTest.php

cd htdocs
php -f dev/tools/Magento/Tools/View/deploy.php
php -f dev/tools/Magento/Tools/Di/compiler.php

# Use developer mode to get more detailed error diagnostics, at least for now.
#echo "SetEnv MAGE_MODE production" >> .htaccess
echo "SetEnv MAGE_MODE developer" >> .htaccess

cd setup
COMPOSER_PROCESS_TIMEOUT=1000 php ../../composer.phar install --profile

chown www-data:www-data -R /var/www/magento2
