#!/bin/bash

# Show what we execute
set -x

# MySQL authentication
MYSQLAUTH="--user=$MYSQL_USER --password=$MYSQL_PASSWORD"

# Wait for MySQL to come up.
until mysql $MYSQLAUTH -e ""; do
    echo "Failed to connect to MySQL - retrying..."
    sleep 1
done

mysql $MYSQLAUTH -e "CREATE DATABASE IF NOT EXISTS magento"

cd /var/www/magento2/htdocs
php -f setup/index.php install \
	--cleanup_database \
	--db_host=mysql \
	--db_name=magento \
	--db_user="$MYSQL_USER" \
	--db_pass="$MYSQL_PASSWORD" \
	--backend_frontname=admin \
	--base_url=http://$PUBLIC_HOST/ \
	--language=en_US \
	--timezone=America/Los_Angeles \
	--currency=USD \
	--admin_lastname=Smith \
	--admin_firstname=John \
	--admin_email=john.smith@example.com \
	--admin_username=admin \
	--admin_password=admin123 \
	--use_secure=0

# In production mode we pre-compute various files
php -f dev/tools/Magento/Tools/View/deploy.php
php -f dev/tools/Magento/Tools/Di/compiler.php

# Run the web server
exec /usr/sbin/apache2 -D FOREGROUND
