#!/bin/bash

# MySQL authentication
MYSQLAUTH="--user=\"$MYSQL_USER\" --password=\"$MYSQL_PASSWORD\""

# Wait for MySQL to come up.
until mysql $MYSQLAUTH -e ""; do
    echo "Failed to connect to MySQL - retrying..."
    sleep 1
done

# Create the database.
mysql $MYSQLAUTH -e "CREATE DATABASE IF NOT EXISTS magento2;"

# Create the Magento local.xml file
sed < /var/www/magento2/htdocs/app/etc/local.xml.template \
    -e "s/{{date}}/<![CDATA[`date`]]>/" \
    -e "s/{{key}}/bfabadc79e44be389494390b63c42114/" \
    -e "s/{{db_prefix}}//" \
    -e "s/{{db_host}}/mysql/" \
    -e "s/{{db_user}}/$MYSQL_USER/" \
    -e "s/{{db_pass}}/$MYSQL_PASSWORD/" \
    -e "s/{{db_name}}/magento2/" \
    -e "s/{{db_init_statements}}/SET NAMES utf8/" \
    -e "s/{{db_model}}/mysql4/" \
    -e "s/{{session_save}}/files/" \
    -e "s/{{backend_frontname}}/backend/" \
    > /var/www/magento2/htdocs/app/etc/local.xml

# Run the web server
echo exec /usr/sbin/apache2 -D FOREGROUND
bash
