#!/bin/bash

# Show what we execute
set -x

# MySQL authentication
MYSQLAUTH="--user=$MYSQL_USER --password=$MYSQL_PASSWORD"

# Wait for MySQL to come up.
until mysql $MYSQLAUTH -e ""; do
    echo "Failed to connect to MySQL - retrying..."
    sleep 1
done

# Ensure we have a fresh database.
mysql $MYSQLAUTH -e "DROP DATABASE IF EXISTS magento2;"
mysql $MYSQLAUTH -e "CREATE DATABASE IF NOT EXISTS magento2;"

# Create the Magento local.xml file
if [ ! -f /var/www/magento2/htdocs/app/etc/local.xml ]; then
    (
	cd /var/www/magento2/htdocs/setup
	php -f index.php install \
		--db_host=mysql \
		--db_name=magento2 \
		--db_user="$MYSQL_USER" \
		--db_pass="$MYSQL_PASSWORD" \
		--backend_frontname=admin \
		--base_url=http://$PUBLIC_HOST/ \
		--language=en_US \
		--timezone=America/Los_Angeles \
		--currency=USD \
		--admin_lastname=Smith \
		--admin_firstname=John \
		--admin_email=john.smith@example.com \
		--admin_username=admin \
		--admin_password=admin123 \
		--use_secure=0
    )
fi

# Run the web server
exec /usr/sbin/apache2 -D FOREGROUND
